# ***Anylitical Photogrammetry HomeWork 4***

KNTU G.E engineering faculty _ 2022 December

*By : Hasti Rafiei Nia*

*Student Code : 9926683*

In [ ]:
from google.colab import files
F = files.upload()

Saving Homework3.xlsx to Homework3 (2).xlsx


In [ ]:
import numpy as np 
import matplotlib.pyplot as plt 
import matplotlib as mpl 
import pandas as pd
import sympy as sp

In [ ]:
df = pd.read_excel(r'Homework3.xlsx')
x = df['x']
y = df['y']
E = df['E']
N = df['N']

Based on distrbution of points we've decided to take points 2,7 & 10 as icps.

In [ ]:
ximage = np.array([[x[0]],
                   [x[2]],
                   [x[3]],
                   [x[4]],
                   [x[5]],
                   [x[7]],
                   [x[8]],
                   [x[10]],
                   [x[11]],
                   [x[12]]])


yimage = np.array([[y[0]],
                   [y[2]],
                   [y[3]],
                   [y[4]],
                   [y[5]],
                   [y[7]],
                   [y[8]],
                   [y[10]],
                   [y[11]],
                   [y[12]]])

xground = np.array([[E[0]],
                   [E[2]],
                   [E[3]],
                   [E[4]],
                   [E[5]],
                   [E[7]],
                   [E[8]],
                   [E[10]],
                   [E[11]],
                   [E[12]]])

yground = np.array([[N[0]],
                   [N[2]],
                   [N[3]],
                   [N[4]],
                   [N[5]],
                   [N[7]],
                   [N[8]],
                   [N[10]],
                   [N[11]],
                   [N[12]]])

checkx = np.array([[x[1]],
                   [x[6]],
                   [x[9]]])

checky= np.array([[y[1]],
                   [y[6]],
                   [y[9]]])

checkE = np.array([[E[1]],
                   [E[6]],
                   [E[9]]])

checkN = np.array([[N[1]],
                   [N[6]],
                   [N[9]]])

# **Part 1**

degree of freedom = 2*10 - 6 = 14

In [ ]:
one = np.ones((10,1))

A1 = np.hstack((one , ximage, yimage))
A1

array([[   1. ,  103. , -100.1],
       [   1. ,  -20. ,  -69. ],
       [   1. ,  -60. ,  -47. ],
       [   1. , -102. ,  -47.2],
       [   1. , -101.7,   10.8],
       [   1. ,  -40. ,   45.7],
       [   1. ,   11. ,   36.8],
       [   1. ,   63. ,   17.7],
       [   1. ,   63. ,   64.3],
       [   1. ,  106. ,   47.7]])

In [ ]:
xcap1 = np.linalg.inv(A1.T @ A1) @ A1.T @ xground
ycap1 = np.linalg.inv(A1.T @ A1) @ A1.T @ yground

a0 = xcap1[0]
a1 = xcap1[1]
a2 = xcap1[2]
b0 = ycap1[0]
b1 = ycap1[1]
b2 = ycap1[2]

print("a0 = " , a0)
print("a1 = " , a1)
print("a2 = " , a2)
print("b0 = " , b0)
print("b1 = " , b1)
print("b2 = " , b2)

a0 =  [504127.28026224]
a1 =  [-39.04565107]
a2 =  [0.0839852]
b0 =  [4999806.87993255]
b1 =  [-0.10174769]
b2 =  [-38.96947017]


In [ ]:
E2 = a0 + a1*x[1] + a2*y[1]
N2 = b0 + b1*x[1] + b2*y[1]

E7 = a0 + a1*x[6] + a2*y[6]
N7 = b0 + b1*x[6] + b2*y[6]

E10 = a0 + a1*x[9] + a2*y[9]
N10 = b0 + b1*x[9] + b2*y[9]

dx2 = checkE[0] - E2
dy2 = checkN[0] - N2

dx7 = checkE[1] - E7 
dy7 = checkN[1] - N7

dx10 = checkE[2] - E10
dy10 = checkN[2] - N10

dr2 = np.sqrt((dx2)**2 + (dy2)**2)
dr7 = np.sqrt((dx7)**2 + (dy7)**2)
dr10 = np.sqrt((dx10)**2 + (dy10)**2)

rmse = np.sqrt(((dr2)**2 + (dr7)**2 + (dr10)**2) / 2)

In [ ]:
print ('Computed coordinates are :')
print("E2 = " , E2 , "N2 = " , N2 )
print("E7 = " , E7 , "N7 = " , N7)
print("E10 = " , E10 , "N10 = " , N10)
print ('Residual vectors are :')
print("dx2 =" , dx2 , "dy2 = " , dy2)
print("dx7 =" , dx7 , "dy7 = " , dy7)
print("dx10 =" , dx10 , "dy10 = " , dy10)
print ('RMSE is :', rmse)

Computed coordinates are :
E2 =  [504090.24036398] N2 =  [5002499.58892329]
E7 =  [507491.57233238] N7 =  [4996861.74439484]
E10 =  [501670.25974178] N10 =  [4998475.50784225]
Residual vectors are :
dx2 = [2.05963602] dy2 =  [-0.08892329]
dx7 = [-15.67233238] dy7 =  [-12.74439484]
dx10 = [-12.35974178] dy10 =  [3.99215775]
RMSE is : [17.04394541]


# **Part 2**

degree of freedom = 2*10 - 12 = 8

In [ ]:
A2 = np.hstack((A1, ximage * yimage , ximage**2 , yimage**2 ))
A2

array([[ 1.000000e+00,  1.030000e+02, -1.001000e+02, -1.031030e+04,
         1.060900e+04,  1.002001e+04],
       [ 1.000000e+00, -2.000000e+01, -6.900000e+01,  1.380000e+03,
         4.000000e+02,  4.761000e+03],
       [ 1.000000e+00, -6.000000e+01, -4.700000e+01,  2.820000e+03,
         3.600000e+03,  2.209000e+03],
       [ 1.000000e+00, -1.020000e+02, -4.720000e+01,  4.814400e+03,
         1.040400e+04,  2.227840e+03],
       [ 1.000000e+00, -1.017000e+02,  1.080000e+01, -1.098360e+03,
         1.034289e+04,  1.166400e+02],
       [ 1.000000e+00, -4.000000e+01,  4.570000e+01, -1.828000e+03,
         1.600000e+03,  2.088490e+03],
       [ 1.000000e+00,  1.100000e+01,  3.680000e+01,  4.048000e+02,
         1.210000e+02,  1.354240e+03],
       [ 1.000000e+00,  6.300000e+01,  1.770000e+01,  1.115100e+03,
         3.969000e+03,  3.132900e+02],
       [ 1.000000e+00,  6.300000e+01,  6.430000e+01,  4.050900e+03,
         3.969000e+03,  4.134490e+03],
       [ 1.000000e+00,  1.060000e+02,

In [ ]:
xcap2 = np.linalg.inv(A2.T @ A2) @ A2.T @ xground
ycap2 = np.linalg.inv(A2.T @ A2) @ A2.T @ yground

a0 = xcap2[0]
a1 = xcap2[1]
a2 = xcap2[2]
a3 = xcap2[3]
a4 = xcap2[4]
a5 = xcap2[5]
b0 = ycap2[0]
b1 = ycap2[1]
b2 = ycap2[2]
b3 = ycap2[3]
b4 = ycap2[4]
b5 = ycap2[5]

print("a0 = " , a0)
print("a1 = " , a1)
print("a2 = " , a2)
print("a3 = " , a3)
print("a4 = " , a4)
print("a5 = " , a5)
print("b0 = " , b0)
print("b1 = " , b1)
print("b2 = " , b2)
print("b3 = " , b3)
print("b4 = " , b4)
print("b5 = " , b5)

a0 =  [504124.65228471]
a1 =  [-39.01286027]
a2 =  [0.00237614]
a3 =  [0.00245037]
a4 =  [-0.00014347]
a5 =  [0.00049612]
b0 =  [4999815.20337444]
b1 =  [-0.02685197]
b2 =  [-39.11891391]
b3 =  [0.00176573]
b4 =  [-0.00084838]
b5 =  [-0.00184791]


In [ ]:
E2 = a0 + a1*x[1] + a2*y[1] + a3*x[1]*y[1] + a4*(x[1]**2) + a5*(y[1]**2)
N2 = b0 + b1*x[1] + b2*y[1] + b3*x[1]*y[1] + b4*(x[1]**2) + b5*(y[1]**2)

E7 = a0 + a1*x[6] + a2*y[6] + a3*x[6]*y[6] + a4*(x[6]**2) + a5*(y[6]**2)
N7 = b0 + b1*x[6] + b2*y[6] + b3*x[6]*y[6] + b4*(x[6]**2) + b5*(y[6]**2)

E10 = a0 + a1*x[9] + a2*y[9] + a3*x[9]*y[9] + a4*(x[9]**2) + a5*(y[9]**2)
N10 = b0 + b1*x[9] + b2*y[9] + b3*x[9]*y[9] + b4*(x[9]**2) + b5*(y[9]**2)

dx2 = checkE[0] - E2
dy2 = checkN[0] - N2

dx7 = checkE[1] - E7 
dy7 = checkN[1] - N7

dx10 = checkE[2] - E10
dy10 = checkN[2] - N10

dr2 = np.sqrt((dx2)**2 + (dy2)**2)
dr7 = np.sqrt((dx7)**2 + (dy7)**2)
dr10 = np.sqrt((dx10)**2 + (dy10)**2)

rmse = np.sqrt(((dr2)**2 + (dr7)**2 + (dr10)**2) / 2)

In [ ]:
print ('Computed coordinates are :')
print("E2 = " , E2 , "N2 = " , N2 )
print("E7 = " , E7 , "N7 = " , N7)
print("E10 = " , E10 , "N10 = " , N10)
print ('Residual vectors are :')
print("dx2 =" , dx2 , "dy2 = " , dy2)
print("dx7 =" , dx7 , "dy7 = " , dy7)
print("dx10 =" , dx10 , "dy10 = " , dy10)
print ('RMSE is :', rmse)

Computed coordinates are :
E2 =  [504095.51115751] N2 =  [5002509.37727696]
E7 =  [507465.75438363] N7 =  [4996823.89647974]
E10 =  [501672.17567173] N10 =  [4998481.74739695]
Residual vectors are :
dx2 = [-3.21115751] dy2 =  [-9.87727696]
dx7 = [10.14561637] dy7 =  [25.10352026]
dx10 = [-14.27567173] dy10 =  [-2.24739695]
RMSE is : [22.91111074]


# **Part 3**

degree of freedom = 2*10 - 20 = 0

In [ ]:
A3 = np.hstack((A2,  (ximage**2)*yimage, (yimage**2)*ximage, ximage**3, yimage**3 ))
A3

array([[ 1.00000000e+00,  1.03000000e+02, -1.00100000e+02,
        -1.03103000e+04,  1.06090000e+04,  1.00200100e+04,
        -1.06196090e+06,  1.03206103e+06,  1.09272700e+06,
        -1.00300300e+06],
       [ 1.00000000e+00, -2.00000000e+01, -6.90000000e+01,
         1.38000000e+03,  4.00000000e+02,  4.76100000e+03,
        -2.76000000e+04, -9.52200000e+04, -8.00000000e+03,
        -3.28509000e+05],
       [ 1.00000000e+00, -6.00000000e+01, -4.70000000e+01,
         2.82000000e+03,  3.60000000e+03,  2.20900000e+03,
        -1.69200000e+05, -1.32540000e+05, -2.16000000e+05,
        -1.03823000e+05],
       [ 1.00000000e+00, -1.02000000e+02, -4.72000000e+01,
         4.81440000e+03,  1.04040000e+04,  2.22784000e+03,
        -4.91068800e+05, -2.27239680e+05, -1.06120800e+06,
        -1.05154048e+05],
       [ 1.00000000e+00, -1.01700000e+02,  1.08000000e+01,
        -1.09836000e+03,  1.03428900e+04,  1.16640000e+02,
         1.11703212e+05, -1.18622880e+04, -1.05187191e+06,
         1.

In [ ]:
xcap3 = np.linalg.inv(A3.T @ A3) @ A3.T @ xground
ycap3 = np.linalg.inv(A3.T @ A3) @ A3.T @ yground

a0 = xcap3[0]
a1 = xcap3[1]
a2 = xcap3[2]
a3 = xcap3[3]
a4 = xcap3[4]
a5 = xcap3[5]
a6 = xcap3[6]
a7 = xcap3[7]
a8 = xcap3[8]
a9 = xcap3[9]
b0 = ycap3[0]
b1 = ycap3[1]
b2 = ycap3[2]
b3 = ycap3[3]
b4 = ycap3[4]
b5 = ycap3[5]
b6 = ycap3[6]
b7 = ycap3[7]
b8 = ycap3[8]
b9 = ycap3[9]

print("a0 = " , a0)
print("a1 = " , a1)
print("a2 = " , a2)
print("a3 = " , a3)
print("a4 = " , a4)
print("a5 = " , a5)
print("a6 = " , a6)
print("a7 = " , a7)
print("a8 = " , a8)
print("a9 = " , a9)

print("b0 = " , b0)
print("b1 = " , b1)
print("b2 = " , b2)
print("b3 = " , b3)
print("b4 = " , b4)
print("b5 = " , b5)
print("b6 = " , b6)
print("b7 = " , b7)
print("b8 = " , b8)
print("b9 = " , b9)

a0 =  [504141.26659867]
a1 =  [-39.01157646]
a2 =  [-1.33670318]
a3 =  [-0.00719184]
a4 =  [0.00172283]
a5 =  [0.00203735]
a6 =  [5.83579471e-06]
a7 =  [9.15047549e-06]
a8 =  [2.95768849e-05]
a9 =  [0.00032092]
b0 =  [4999836.25401631]
b1 =  [-0.25274146]
b2 =  [-39.89123353]
b3 =  [-0.00129473]
b4 =  [-0.00120547]
b5 =  [-0.00520118]
b6 =  [-1.10793243e-05]
b7 =  [6.84403348e-05]
b8 =  [3.20035175e-05]
b9 =  [0.00018509]


In [ ]:
E2 = a0 + a1*x[1] + a2*y[1] + a3*x[1]*y[1] + a4*(x[1]**2) + a5*(y[1]**2) + a6*((x[1]**2)*y[1]) + a7*(x[1]*(y[1]**2)) + a8*(x[1]**3) + a9*(y[1]**3)
N2 = b0 + b1*x[1] + b2*y[1] + b3*x[1]*y[1] + b4*(x[1]**2) + b5*(y[1]**2) + b6*((x[1]**2)*y[1]) + b7*(x[1]*(y[1]**2)) + b8*(x[1]**3) + b9*(y[1]**3)

E7 = a0 + a1*x[6] + a2*y[6] + a3*x[6]*y[6] + a4*(x[6]**2) + a5*(y[6]**2) + a6*((x[6]**2)*y[6]) + a7*(x[6]*(y[6]**2)) + a8*(x[6]**3) + a9*(y[6]**3)
N7 = b0 + b1*x[6] + b2*y[6] + b3*x[6]*y[6] + b4*(x[6]**2) + b5*(y[6]**2) + b6*((x[6]**2)*y[6]) + b7*(x[6]*(y[6]**2)) + b8*(x[6]**3) + b9*(y[6]**3)

E10 = a0 + a1*x[9] + a2*y[9] + a3*x[9]*y[9] + a4*(x[9]**2) + a5*(y[9]**2) + a6*((x[9]**2)*y[9]) + a7*(x[9]*(y[9]**2)) + a8*(x[9]**3) + a9*(y[9]**3)
N10 = b0 + b1*x[9] + b2*y[9] + b3*x[9]*y[9] + b4*(x[9]**2) + b5*(y[9]**2) + b6*((x[9]**2)*y[9]) + b7*(x[9]*(y[9]**2)) + b8*(x[9]**3) + b9*(y[9]**3)

dx2 = checkE[0] - E2
dy2 = checkN[0] - N2

dx7 = checkE[1] - E7 
dy7 = checkN[1] - N7

dx10 = checkE[2] - E10
dy10 = checkN[2] - N10

dr2 = np.sqrt((dx2)**2 + (dy2)**2)
dr7 = np.sqrt((dx7)**2 + (dy7)**2)
dr10 = np.sqrt((dx10)**2 + (dy10)**2)

rmse = np.sqrt(((dr2)**2 + (dr7)**2 + (dr10)**2) / 2)

In [ ]:
print ('Computed coordinates are :')
print("E2 = " , E2 , "N2 = " , N2 )
print("E7 = " , E7 , "N7 = " , N7)
print("E10 = " , E10 , "N10 = " , N10)
print ('Residual vectors are :')
print("dx2 =" , dx2 , "dy2 = " , dy2)
print("dx7 =" , dx7 , "dy7 = " , dy7)
print("dx10 =" , dx10 , "dy10 = " , dy10)
print ('RMSE is :', rmse)

Computed coordinates are :
E2 =  [504106.69995879] N2 =  [5002506.96429882]
E7 =  [507585.97575097] N7 =  [4996824.10133416]
E10 =  [501653.34061755] N10 =  [4998469.22557173]
Residual vectors are :
dx2 = [-14.39995879] dy2 =  [-7.46429882]
dx7 = [-110.07575097] dy7 =  [24.89866584]
dx10 = [4.55938245] dy10 =  [10.27442827]
RMSE is : [81.01247104]


Based on results we can say that part 3 is an over parameterization and an ill condition.

But we can have better results using repeat loop on terms of part 2 and eliminating some terms.