# ***Anylitical Photogrammetry HomeWork 3***

KNTU G.E engineering faculty _ 2022 December

*By : Hasti Rafiei Nia*

*Student Code : 9926683*

Getting familiar with basic python commands.

In [ ]:
import numpy as np

# ***part1***

# **np.array**

Forms a matrix.

numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)

In [ ]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

# **np.zeros**

Returns a new array of given shape and type, filled with zeros.

numpy.zeros(shape, dtype=float, order='C', *, like=None)

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

# **np.sqrt**

Takes the root of the input.

In [ ]:
np.sqrt([1,4,9])

array([1., 2., 3.])

# **np.floor**

Returns the floor of the input, element-wise.

numpy.floor(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

In [ ]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

# **.len()**

Returns the number of items in a list.

In [ ]:
mylist = ["apple", "banana", "cherry"]
len(mylist)

3

# **np.linalg.matrix_rank()**

Returns matrix rank of array using SVD method.

linalg.matrix_rank(A, tol=None, hermitian=False)

In [ ]:
np.linalg.matrix_rank(np.eye(4))

4

In [ ]:
np.linalg.matrix_rank(np.ones((4,)))

1

# **.dot()**

function is used to return the dot product of given arrays

In [ ]:
arr = np.array([3, 1, 9, 7])
arr1 = np.array([2, 6, 4, 8])
np.dot(arr, arr1)

104

# **np.arrange**

Returns evenly spaced values within a given interval.

numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)

In [ ]:
np.arange(-3, 3, 0.5, dtype=int)

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

# **np.ones**

Returns a new array of given shape and type, filled with ones.

numpy.ones(shape, dtype=None, order='C', *, like=None)

In [ ]:
np.ones((2, 1))

array([[1.],
       [1.]])

# **np.exp**

Calculates the exponential of all elements in the input array.

numpy.exp(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True)

In [ ]:
x = np.linspace(-2*np.pi, 2*np.pi, 100)
np.exp(x)


array([1.86744273e-03, 2.12018428e-03, 2.40713211e-03, 2.73291575e-03,
       3.10279128e-03, 3.52272611e-03, 3.99949535e-03, 4.54079101e-03,
       5.15534615e-03, 5.85307580e-03, 6.64523686e-03, 7.54460979e-03,
       8.56570474e-03, 9.72499569e-03, 1.10411862e-02, 1.25355113e-02,
       1.42320798e-02, 1.61582635e-02, 1.83451389e-02, 2.08279881e-02,
       2.36468686e-02, 2.68472592e-02, 3.04807938e-02, 3.46060946e-02,
       3.92897177e-02, 4.46072269e-02, 5.06444131e-02, 5.74986781e-02,
       6.52806060e-02, 7.41157478e-02, 8.41466464e-02, 9.55351367e-02,
       1.08464957e-01, 1.23144711e-01, 1.39811238e-01, 1.58733429e-01,
       1.80216569e-01, 2.04607257e-01, 2.32299006e-01, 2.63738583e-01,
       2.99433223e-01, 3.39958812e-01, 3.85969174e-01, 4.38206623e-01,
       4.97513941e-01, 5.64847970e-01, 6.41295052e-01, 7.28088559e-01,
       8.26628784e-01, 9.38505542e-01, 1.06552381e+00, 1.20973286e+00,
       1.37345930e+00, 1.55934464e+00, 1.77038788e+00, 2.00999393e+00,
      

# **np.vstack**

function in Python is used to stack or concate the sequence of given arrays vertically(row-wise)

In [ ]:
arr = np.array([1, 2, 3])
arr1 = np.array([4, 5, 6])
np.vstack((arr, arr1))

array([[1, 2, 3],
       [4, 5, 6]])

# **.shape()**

Is used to fetch the dimensions of Pandas and NumPy type objects in python.

In [ ]:
ar = np.array([[12,20] ,[13,15]])
ar.shape

(2, 2)

# **np.linalg.det**

Computes the determinant of an array.

In [ ]:
a = np.array([[1, 2], [3, 4]])
np.linalg.det(a)

-2.0000000000000004

In [ ]:
a = np.array([ [[1, 2], [3, 4]], [[1, 2], [2, 1]], [[1, 3], [3, 1]] ])
np.linalg.det(a)

array([-2., -3., -8.])

# **.transpose()**

function to get the permute or reserve the dimension of the input matrix

In [ ]:
np.transpose([[1, 2, 4, 3],[1, 3, 5, 6]])

array([[1, 1],
       [2, 3],
       [4, 5],
       [3, 6]])

# **np.reshape**

Gives a new shape to an array without changing its data.

numpy.reshape(a, newshape, order='C')

In [ ]:
a = np.array([[1,2,3], [4,5,6]])
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

# **np.linspace**

Returns evenly spaced numbers over a specified interval.

numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [ ]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

# **.T**

Is used to transpose index and columns of the data frame.

In [ ]:
a = np.array([[1, 2], [3, 4]])
a.T

array([[1, 3],
       [2, 4]])

# **np.hstack**

Is used to stack or concatenate arrays in sequence horizontally (column-wise).

In [ ]:
arr = np.array([ 2, 3, 4])
arr1 = np.array([5, 6, 7])
np.hstack((arr,arr1))

array([2, 3, 4, 5, 6, 7])

# **np.isnan**

Tests element-wise for NaN and return result as a boolean array.

numpy.isnan(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True)

In [ ]:
np.isnan([np.log(-1.),1.,np.log(0)])

<ipython-input-37-896a599b4ca8>:1: RuntimeWarning: invalid value encountered in log
  np.isnan([np.log(-1.),1.,np.log(0)])
<ipython-input-37-896a599b4ca8>:1: RuntimeWarning: divide by zero encountered in log
  np.isnan([np.log(-1.),1.,np.log(0)])


array([ True, False, False])

# **np.linalg.eig**

Computes the eigenvalues and right eigenvectors of a square array.

In [ ]:
w, v = np.linalg.eig(np.array([[1, -1], [1, 1]]))
w; v

array([[0.70710678+0.j        , 0.70710678-0.j        ],
       [0.        -0.70710678j, 0.        +0.70710678j]])

array([[0.70710678+0.j        , 0.70710678-0.j        ],
       [0.        -0.70710678j, 0.        +0.70710678j]])

# **np.matmul**

Matrix product of two arrays.

numpy.matmul(x1, x2, /, out=None, *, casting='same_kind', order='K', dtype=None, subok=True)

In [ ]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])
np.matmul(a, b)

array([[4, 1],
       [2, 2]])

# ***Part 2***

# **np.full**

Returns a new array of given shape and type, filled with fill_value.

numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)

In [ ]:
np.full((2, 2), np.inf)

array([[inf, inf],
       [inf, inf]])

# **np.eye**

Returns a 2D array with ones on the diagonal and zeros elsewhere.

numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)

In [ ]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

# **np.random.random**

Returns random floats in the half-open interval [0.0, 1.0). Alias for random_sample to ease forward-porting to the new random API.



In [ ]:
np.random.random((3 ,3))

array([[0.50136245, 0.90818796, 0.48976864],
       [0.28264815, 0.58773104, 0.77221512],
       [0.06429264, 0.08886457, 0.46831983]])

array([[0.8101994 , 0.22368539, 0.03298513],
       [0.9311727 , 0.2377579 , 0.24349352],
       [0.70949932, 0.33564099, 0.81846647]])

# **np.empty**

Return a new array of given shape and type, without initializing entries.

numpy.empty(shape, dtype=float, order='C', *, like=None)

In [ ]:
np.empty([2, 2])

array([[4.9e-324, 9.9e-324],
       [1.5e-323, 2.0e-323]])

#**np.save**

Saves an array to a binary file in NumPy .npy format.

numpy.save(file, arr, allow_pickle=True, fix_imports=True)

In [ ]:
with open('test.npy', 'wb') as f:
 np.save(f, np.array([1, 2]))
 np.save(f, np.array([1, 3]))
 with open('test.npy', 'rb') as f:
    a = np.load(f)
    b = np.load(f)
print(a,b)

[1 2] [1 3]


# **np.saves**

Saves several arrays into a single file in uncompressed .npz format.

numpy.savez(file, *args, **kwds)

# **np.load**

Loads arrays or pickled objects from .npy, .npz or pickled files.

numpy.load(file, mmap_mode=None, allow_pickle=False, fix_imports=True, encoding='ASCII')


In [ ]:
np.save('/tmp/123', np.array([[1, 2, 3], [4, 5, 6]]))
np.load('/tmp/123.npy')

array([[1, 2, 3],
       [4, 5, 6]])

# **b.ndim**

Number of array dimensions.

In [ ]:
x = np.array([1, 2, 3])
b.ndim

1

# **e.size**

counts the number of elements along a given axis.

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
np.size(arr)

8

# **b.dtype**



In [ ]:
dt = np.dtype('>i4')
dt.byteorder

'>'

# **b.dtype.name**

A bit-width name for this data-type.

In [ ]:
x = np.dtype([('a', np.int32, 8), ('b', np.float64, 6)])
x.name

'void640'

# **np.substract , np.add , np.divide , np.multiply**

Subtract, add, divide & multiply arguments, element-wise.

numpy.subtract(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True)

numpy.add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True)

numpy.divide(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True)

numpy.multiply(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True)

In [ ]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
np.subtract(x1, x2)

array([[0., 0., 0.],
       [3., 3., 3.],
       [6., 6., 6.]])

In [ ]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
np.add(x1, x2)

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.]])

In [ ]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
np.divide(x1, x2)

<ipython-input-67-3d28a0269857>:3: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(x1, x2)
<ipython-input-67-3d28a0269857>:3: RuntimeWarning: invalid value encountered in true_divide
  np.divide(x1, x2)


array([[nan, 1. , 1. ],
       [inf, 4. , 2.5],
       [inf, 7. , 4. ]])

In [ ]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

# **np.sin , np.cos , np.log**

Trigonometric sine,cosine and logaritm element-wise.

numpy.sin(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True)

numpy.cos(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True)

numpy.log(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True)

In [ ]:
np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180. )

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [ ]:
np.cos(np.array([0, np.pi/2, np.pi]))

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [ ]:
np.log([1, np.e, np.e**2, 0])

<ipython-input-14-12cefd5fc7db>:1: RuntimeWarning: divide by zero encountered in log
  np.log([1, np.e, np.e**2, 0])


array([  0.,   1.,   2., -inf])

# **np.array_equal**

True if two arrays have the same shape and elements, False otherwise.

numpy.array_equal(a1, a2, equal_nan=False)

In [ ]:
np.array_equal([1, 2], [1, 2, 3])

False

In [ ]:
np.array_equal([1, 2], [1, 2])

True

# **a.sum() , a.min() , a.max()**

Sum, minimum & maximum of array elements over a given axis.

numpy.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)

numpy.min(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)

numpy.max(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)

In [ ]:
np.sum([0.5, 1.5])

2.0

In [ ]:
a = np.arange(4).reshape((2,2))
np.min(a)

0

In [ ]:
a = np.arange(4).reshape((2,2))
np.max(a)

3

# **a.mean()**

Computes the arithmetic mean along the specified axis or returns the average of the array elements. 


numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)

In [ ]:
a = np.array([[1, 2], [3, 4]])
np.mean(a)

# **np.median**

Computes the median along the specified axis or returns the median of the array elements.



numpy.median(a, axis=None, out=None, overwrite_input=False, keepdims=False)

In [ ]:
a = np.array([[10, 7, 4], [3, 2, 1]])
np.median(a)

3.5

# **np.std**

Computes the standard deviation along the specified axisor returns the standard deviation, a measure of the spread of a distribution, of the array elements.

numpy.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>, *, where=<no value>)

In [ ]:
a = np.array([[1, 2], [3, 4]])
np.std(a)

1.118033988749895

# **np.corrcoef**

Returns Pearson product-moment correlation coefficients.

numpy.corrcoef(x, y=None, rowvar=True, bias=<no value>, ddof=<no value>, *, dtype=None)

In [ ]:
xarr = np.random.random((3, 3))
yarr = np.random.random((3, 3))
np.corrcoef(xarr, yarr)

array([[ 1.        ,  0.37395416, -0.6072775 ,  0.34263643, -0.84061592,
         0.6054355 ],
       [ 0.37395416,  1.        ,  0.50975338,  0.99943735,  0.18798296,
         0.96455512],
       [-0.6072775 ,  0.50975338,  1.        ,  0.53832241,  0.94080798,
         0.2646626 ],
       [ 0.34263643,  0.99943735,  0.53832241,  1.        ,  0.22082004,
         0.95516162],
       [-0.84061592,  0.18798296,  0.94080798,  0.22082004,  1.        ,
        -0.07785711],
       [ 0.6054355 ,  0.96455512,  0.2646626 ,  0.95516162, -0.07785711,
         1.        ]])

# **np.copy**

Returns an array copy of the given object.

numpy.copy(a, order='K', subok=False)

In [ ]:
a = np.array([1, 2, 3])
a.flags["WRITEABLE"] = False
b = np.copy(a)
b.flags["WRITEABLE"]

True

# **np.sort**

Returns a sorted copy of an array.

numpy.sort(a, axis=- 1, kind=None, order=None)

In [ ]:
a = np.array([[1,4],[3,1]])
np.sort(a) 

array([[1, 4],
       [1, 3]])